// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.34438 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>GeneriCode.GeneratedClasses.Genericode.v10</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneriCode.GeneratedClasses.Genericode.v10
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class CodeListDocument
    {

        private Annotation annotationField;

        private Identification identificationField;

        private ColumnSet columnSetField;

        private ColumnSetRef columnSetRefField;

        private SimpleCodeList simpleCodeListField;

        private string baseField;

        public CodeListDocument()
        {
            this.simpleCodeListField = new SimpleCodeList();
            this.columnSetRefField = new ColumnSetRef();
            this.columnSetField = new ColumnSet();
            this.identificationField = new Identification();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public Identification Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }

        public ColumnSet ColumnSet
        {
            get
            {
                return this.columnSetField;
            }
            set
            {
                this.columnSetField = value;
            }
        }

        public ColumnSetRef ColumnSetRef
        {
            get
            {
                return this.columnSetRefField;
            }
            set
            {
                this.columnSetRefField = value;
            }
        }

        public SimpleCodeList SimpleCodeList
        {
            get
            {
                return this.simpleCodeListField;
            }
            set
            {
                this.simpleCodeListField = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
    }

    public partial class Annotation
    {

        private List<AnyOtherLanguageContent> descriptionField;

        private AnyOtherContent appInfoField;

        public Annotation()
        {
            this.appInfoField = new AnyOtherContent();
            this.descriptionField = new List<AnyOtherLanguageContent>();
        }

        public List<AnyOtherLanguageContent> Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        public AnyOtherContent AppInfo
        {
            get
            {
                return this.appInfoField;
            }
            set
            {
                this.appInfoField = value;
            }
        }
    }

    public partial class AnyOtherLanguageContent : AnyOtherContent
    {

        private string langField;

        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnyOtherLanguageContent))]
    public partial class AnyOtherContent
    {

        private List<System.Xml.XmlElement> anyField;

        public AnyOtherContent()
        {
            this.anyField = new List<System.Xml.XmlElement>();
        }

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlElement> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    public partial class SimpleValue
    {

        private string valueField;

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public partial class Value
    {

        private Annotation annotationField;

        private SimpleValue simpleValueField;

        private AnyOtherContent complexValueField;

        private string columnRefField;

        public Value()
        {
            this.complexValueField = new AnyOtherContent();
            this.simpleValueField = new SimpleValue();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public SimpleValue SimpleValue
        {
            get
            {
                return this.simpleValueField;
            }
            set
            {
                this.simpleValueField = value;
            }
        }

        public AnyOtherContent ComplexValue
        {
            get
            {
                return this.complexValueField;
            }
            set
            {
                this.complexValueField = value;
            }
        }

        public string ColumnRef
        {
            get
            {
                return this.columnRefField;
            }
            set
            {
                this.columnRefField = value;
            }
        }
    }

    public partial class Row
    {

        private Annotation annotationField;

        private List<Value> valueField;

        public Row()
        {
            this.valueField = new List<Value>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public List<Value> Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public partial class SimpleCodeList
    {

        private Annotation annotationField;

        private List<Row> rowField;

        public SimpleCodeList()
        {
            this.rowField = new List<Row>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public List<Row> Row
        {
            get
            {
                return this.rowField;
            }
            set
            {
                this.rowField = value;
            }
        }
    }

    public partial class ColumnSetRef
    {

        private Annotation annotationField;

        private string canonicalVersionUriField;

        private List<string> locationUriField;

        private string baseField;

        public ColumnSetRef()
        {
            this.locationUriField = new List<string>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public string CanonicalVersionUri
        {
            get
            {
                return this.canonicalVersionUriField;
            }
            set
            {
                this.canonicalVersionUriField = value;
            }
        }

        public List<string> LocationUri
        {
            get
            {
                return this.locationUriField;
            }
            set
            {
                this.locationUriField = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
    }

    public partial class KeyRef
    {

        private Annotation annotationField;

        private string canonicalVersionUriField;

        private List<string> locationUriField;

        private string idField;

        private string externalRefField;

        private string baseField;

        public KeyRef()
        {
            this.locationUriField = new List<string>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public string CanonicalVersionUri
        {
            get
            {
                return this.canonicalVersionUriField;
            }
            set
            {
                this.canonicalVersionUriField = value;
            }
        }

        public List<string> LocationUri
        {
            get
            {
                return this.locationUriField;
            }
            set
            {
                this.locationUriField = value;
            }
        }

        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string ExternalRef
        {
            get
            {
                return this.externalRefField;
            }
            set
            {
                this.externalRefField = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
    }

    public partial class KeyColumnRef
    {

        private Annotation annotationField;

        private string refField;

        public KeyColumnRef()
        {
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public string Ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
    }

    public partial class Key
    {

        private Annotation annotationField;

        private ShortName shortNameField;

        private List<LongName> longNameField;

        private string canonicalUriField;

        private string canonicalVersionUriField;

        private List<KeyColumnRef> columnRefField;

        private string idField;

        public Key()
        {
            this.columnRefField = new List<KeyColumnRef>();
            this.longNameField = new List<LongName>();
            this.shortNameField = new ShortName();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public ShortName ShortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }

        public List<LongName> LongName
        {
            get
            {
                return this.longNameField;
            }
            set
            {
                this.longNameField = value;
            }
        }

        public string CanonicalUri
        {
            get
            {
                return this.canonicalUriField;
            }
            set
            {
                this.canonicalUriField = value;
            }
        }

        public string CanonicalVersionUri
        {
            get
            {
                return this.canonicalVersionUriField;
            }
            set
            {
                this.canonicalVersionUriField = value;
            }
        }

        public List<KeyColumnRef> ColumnRef
        {
            get
            {
                return this.columnRefField;
            }
            set
            {
                this.columnRefField = value;
            }
        }

        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    public partial class ShortName
    {

        private string langField;

        private string valueField;

        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType = "token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public partial class LongName
    {

        private string identifierField;

        private string langField;

        private string valueField;

        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType = "normalizedString")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public partial class DataRestrictions
    {

        private List<DatatypeFacet> parameterField;

        private string langField;

        public DataRestrictions()
        {
            this.parameterField = new List<DatatypeFacet>();
        }

        public List<DatatypeFacet> Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }

        public string Lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
    }

    public partial class DatatypeFacet
    {

        private string shortNameField;

        private string longNameField;

        private string valueField;

        public string ShortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }

        public string LongName
        {
            get
            {
                return this.longNameField;
            }
            set
            {
                this.longNameField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public partial class ColumnRef
    {

        private Annotation annotationField;

        private string canonicalVersionUriField;

        private List<string> locationUriField;

        private DataRestrictions dataField;

        private string idField;

        private string externalRefField;

        private UseType useField;

        private bool useFieldSpecified;

        private string baseField;

        public ColumnRef()
        {
            this.dataField = new DataRestrictions();
            this.locationUriField = new List<string>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public string CanonicalVersionUri
        {
            get
            {
                return this.canonicalVersionUriField;
            }
            set
            {
                this.canonicalVersionUriField = value;
            }
        }

        public List<string> LocationUri
        {
            get
            {
                return this.locationUriField;
            }
            set
            {
                this.locationUriField = value;
            }
        }

        public DataRestrictions Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string ExternalRef
        {
            get
            {
                return this.externalRefField;
            }
            set
            {
                this.externalRefField = value;
            }
        }

        public UseType Use
        {
            get
            {
                return this.useField;
            }
            set
            {
                this.useField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseSpecified
        {
            get
            {
                return this.useFieldSpecified;
            }
            set
            {
                this.useFieldSpecified = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
    }

    public enum UseType
    {

        /// <remarks/>
        optional,

        /// <remarks/>
        required,
    }

    public partial class Data
    {

        private Annotation annotationField;

        private List<DatatypeFacet> parameterField;

        private string typeField;

        private string datatypeLibraryField;

        private string langField;

        public Data()
        {
            this.parameterField = new List<DatatypeFacet>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public List<DatatypeFacet> Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }

        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        public string DatatypeLibrary
        {
            get
            {
                return this.datatypeLibraryField;
            }
            set
            {
                this.datatypeLibraryField = value;
            }
        }

        public string Lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
    }

    public partial class Column
    {

        private Annotation annotationField;

        private ShortName shortNameField;

        private List<LongName> longNameField;

        private string canonicalUriField;

        private string canonicalVersionUriField;

        private Data dataField;

        private string idField;

        private UseType useField;

        public Column()
        {
            this.dataField = new Data();
            this.longNameField = new List<LongName>();
            this.shortNameField = new ShortName();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public ShortName ShortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }

        public List<LongName> LongName
        {
            get
            {
                return this.longNameField;
            }
            set
            {
                this.longNameField = value;
            }
        }

        public string CanonicalUri
        {
            get
            {
                return this.canonicalUriField;
            }
            set
            {
                this.canonicalUriField = value;
            }
        }

        public string CanonicalVersionUri
        {
            get
            {
                return this.canonicalVersionUriField;
            }
            set
            {
                this.canonicalVersionUriField = value;
            }
        }

        public Data Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public UseType Use
        {
            get
            {
                return this.useField;
            }
            set
            {
                this.useField = value;
            }
        }
    }

    public partial class ColumnSet
    {

        private List<Column> columnField;

        private List<ColumnRef> columnRefField;

        private List<Key> keyField;

        private List<KeyRef> keyRefField;

        private string datatypeLibraryField;

        private string baseField;

        public ColumnSet()
        {
            this.keyRefField = new List<KeyRef>();
            this.keyField = new List<Key>();
            this.columnRefField = new List<ColumnRef>();
            this.columnField = new List<Column>();
            this.datatypeLibraryField = "http://www.w3.org/2001/XMLSchema-datatypes";
        }

        public List<Column> Column
        {
            get
            {
                return this.columnField;
            }
            set
            {
                this.columnField = value;
            }
        }

        public List<ColumnRef> ColumnRef
        {
            get
            {
                return this.columnRefField;
            }
            set
            {
                this.columnRefField = value;
            }
        }

        public List<Key> Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        public List<KeyRef> KeyRef
        {
            get
            {
                return this.keyRefField;
            }
            set
            {
                this.keyRefField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("http://www.w3.org/2001/XMLSchema-datatypes")]
        public string DatatypeLibrary
        {
            get
            {
                return this.datatypeLibraryField;
            }
            set
            {
                this.datatypeLibraryField = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
    }

    public partial class GeneralIdentifier
    {

        private string identifierField;

        private string langField;

        private string valueField;

        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType = "normalizedString")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public partial class Agency
    {

        private ShortName shortNameField;

        private List<LongName> longNameField;

        private List<GeneralIdentifier> identifierField;

        public Agency()
        {
            this.identifierField = new List<GeneralIdentifier>();
            this.longNameField = new List<LongName>();
            this.shortNameField = new ShortName();
        }

        public ShortName ShortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }

        public List<LongName> LongName
        {
            get
            {
                return this.longNameField;
            }
            set
            {
                this.longNameField = value;
            }
        }

        public List<GeneralIdentifier> Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
    }

    public partial class MimeTypedUri
    {

        private string mimeTypeField;

        private string valueField;

        public string MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType = "anyURI")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public partial class Identification
    {

        private ShortName shortNameField;

        private List<LongName> longNameField;

        private string versionField;

        private string canonicalUriField;

        private string canonicalVersionUriField;

        private List<string> locationUriField;

        private List<MimeTypedUri> alternateFormatLocationUriField;

        private Agency agencyField;

        public Identification()
        {
            this.agencyField = new Agency();
            this.alternateFormatLocationUriField = new List<MimeTypedUri>();
            this.locationUriField = new List<string>();
            this.longNameField = new List<LongName>();
            this.shortNameField = new ShortName();
        }

        public ShortName ShortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }

        public List<LongName> LongName
        {
            get
            {
                return this.longNameField;
            }
            set
            {
                this.longNameField = value;
            }
        }

        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        public string CanonicalUri
        {
            get
            {
                return this.canonicalUriField;
            }
            set
            {
                this.canonicalUriField = value;
            }
        }

        public string CanonicalVersionUri
        {
            get
            {
                return this.canonicalVersionUriField;
            }
            set
            {
                this.canonicalVersionUriField = value;
            }
        }

        public List<string> LocationUri
        {
            get
            {
                return this.locationUriField;
            }
            set
            {
                this.locationUriField = value;
            }
        }

        public List<MimeTypedUri> AlternateFormatLocationUri
        {
            get
            {
                return this.alternateFormatLocationUriField;
            }
            set
            {
                this.alternateFormatLocationUriField = value;
            }
        }

        public Agency Agency
        {
            get
            {
                return this.agencyField;
            }
            set
            {
                this.agencyField = value;
            }
        }
    }

    public partial class CodeListSetDocument
    {

        private Annotation annotationField;

        private Identification identificationField;

        private List<CodeListRef> codeListRefField;

        private List<CodeListSetDocument> codeListSetField;

        private List<CodeListSetRef> codeListSetRefField;

        private string baseField;

        public CodeListSetDocument()
        {
            this.codeListSetRefField = new List<CodeListSetRef>();
            this.codeListSetField = new List<CodeListSetDocument>();
            this.codeListRefField = new List<CodeListRef>();
            this.identificationField = new Identification();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public Identification Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }

        public List<CodeListRef> CodeListRef
        {
            get
            {
                return this.codeListRefField;
            }
            set
            {
                this.codeListRefField = value;
            }
        }

        public List<CodeListSetDocument> CodeListSet
        {
            get
            {
                return this.codeListSetField;
            }
            set
            {
                this.codeListSetField = value;
            }
        }

        public List<CodeListSetRef> CodeListSetRef
        {
            get
            {
                return this.codeListSetRefField;
            }
            set
            {
                this.codeListSetRefField = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
    }

    public partial class CodeListRef
    {

        private Annotation annotationField;

        private string canonicalUriField;

        private string canonicalVersionUriField;

        private List<string> locationUriField;

        private string baseField;

        public CodeListRef()
        {
            this.locationUriField = new List<string>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public string CanonicalUri
        {
            get
            {
                return this.canonicalUriField;
            }
            set
            {
                this.canonicalUriField = value;
            }
        }

        public string CanonicalVersionUri
        {
            get
            {
                return this.canonicalVersionUriField;
            }
            set
            {
                this.canonicalVersionUriField = value;
            }
        }

        public List<string> LocationUri
        {
            get
            {
                return this.locationUriField;
            }
            set
            {
                this.locationUriField = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
    }

    public partial class CodeListSetRef
    {

        private Annotation annotationField;

        private string canonicalUriField;

        private string canonicalVersionUriField;

        private List<string> locationUriField;

        private string baseField;

        public CodeListSetRef()
        {
            this.locationUriField = new List<string>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public string CanonicalUri
        {
            get
            {
                return this.canonicalUriField;
            }
            set
            {
                this.canonicalUriField = value;
            }
        }

        public string CanonicalVersionUri
        {
            get
            {
                return this.canonicalVersionUriField;
            }
            set
            {
                this.canonicalVersionUriField = value;
            }
        }

        public List<string> LocationUri
        {
            get
            {
                return this.locationUriField;
            }
            set
            {
                this.locationUriField = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
    }

    public partial class ColumnSetDocument
    {

        private Annotation annotationField;

        private Identification identificationField;

        private List<Column> columnField;

        private List<ColumnRef> columnRefField;

        private List<Key> keyField;

        private List<KeyRef> keyRefField;

        private string datatypeLibraryField;

        private string baseField;

        public ColumnSetDocument()
        {
            this.keyRefField = new List<KeyRef>();
            this.keyField = new List<Key>();
            this.columnRefField = new List<ColumnRef>();
            this.columnField = new List<Column>();
            this.identificationField = new Identification();
            this.annotationField = new Annotation();
            this.datatypeLibraryField = "http://www.w3.org/2001/XMLSchema-datatypes";
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public Identification Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }

        public List<Column> Column
        {
            get
            {
                return this.columnField;
            }
            set
            {
                this.columnField = value;
            }
        }

        public List<ColumnRef> ColumnRef
        {
            get
            {
                return this.columnRefField;
            }
            set
            {
                this.columnRefField = value;
            }
        }

        public List<Key> Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        public List<KeyRef> KeyRef
        {
            get
            {
                return this.keyRefField;
            }
            set
            {
                this.keyRefField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("http://www.w3.org/2001/XMLSchema-datatypes")]
        public string DatatypeLibrary
        {
            get
            {
                return this.datatypeLibraryField;
            }
            set
            {
                this.datatypeLibraryField = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
    }
}
