// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.34438 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>GeneriCode.GeneratedClasses.CVA.v10</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneriCode.GeneratedClasses.CVA.v10
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class ContextValueAssociation
    {

        private Annotation annotationField;

        private Title titleField;

        private List<Include> includeField;

        private ValueTests valueTestsField;

        private ValueLists valueListsField;

        private InstanceMetadataSets instanceMetadataSetsField;

        private Contexts contextsField;

        private string idField;

        private string nameField;

        private string versionField;

        private string queryBindingField;

        private string baseField;

        public ContextValueAssociation()
        {
            this.contextsField = new Contexts();
            this.instanceMetadataSetsField = new InstanceMetadataSets();
            this.valueListsField = new ValueLists();
            this.valueTestsField = new ValueTests();
            this.includeField = new List<Include>();
            this.titleField = new Title();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public Title Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        public List<Include> Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }

        public ValueTests ValueTests
        {
            get
            {
                return this.valueTestsField;
            }
            set
            {
                this.valueTestsField = value;
            }
        }

        public ValueLists ValueLists
        {
            get
            {
                return this.valueListsField;
            }
            set
            {
                this.valueListsField = value;
            }
        }

        public InstanceMetadataSets InstanceMetadataSets
        {
            get
            {
                return this.instanceMetadataSetsField;
            }
            set
            {
                this.instanceMetadataSetsField = value;
            }
        }

        public Contexts Contexts
        {
            get
            {
                return this.contextsField;
            }
            set
            {
                this.contextsField = value;
            }
        }

        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        public string queryBinding
        {
            get
            {
                return this.queryBindingField;
            }
            set
            {
                this.queryBindingField = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
    }

    public partial class Annotation
    {

        private List<AnnotationDescription> descriptionField;

        private AnnotationAppInfo appInfoField;

        public Annotation()
        {
            this.appInfoField = new AnnotationAppInfo();
            this.descriptionField = new List<AnnotationDescription>();
        }

        public List<AnnotationDescription> Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        public AnnotationAppInfo AppInfo
        {
            get
            {
                return this.appInfoField;
            }
            set
            {
                this.appInfoField = value;
            }
        }
    }

    public partial class AnnotationDescription
    {

        private List<System.Xml.XmlNode> anyField;

        private string langField;

        public AnnotationDescription()
        {
            this.anyField = new List<System.Xml.XmlNode>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlNode> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
    }

    public partial class Message
    {

        private List<System.Xml.XmlNode> anyField;

        private string useUriField;

        public Message()
        {
            this.anyField = new List<System.Xml.XmlNode>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlNode> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        public string useUri
        {
            get
            {
                return this.useUriField;
            }
            set
            {
                this.useUriField = value;
            }
        }
    }

    public partial class Context
    {

        private Annotation annotationField;

        private List<Message> messageField;

        private string metadataField;

        private string addressField;

        private string valuesField;

        private string markField;

        public Context()
        {
            this.messageField = new List<Message>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public List<Message> Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        public string metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }

        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        public string values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }

        public string mark
        {
            get
            {
                return this.markField;
            }
            set
            {
                this.markField = value;
            }
        }
    }

    public partial class Contexts
    {

        private Annotation annotationField;

        private List<Context> contextField;

        public Contexts()
        {
            this.contextField = new List<Context>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public List<Context> Context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
    }

    public partial class InstanceMetadata
    {

        private Annotation annotationField;

        private string addressField;

        private string identificationField;

        public InstanceMetadata()
        {
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        public string identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }
    }

    public partial class InstanceMetadataSet
    {

        private Annotation annotationField;

        private List<InstanceMetadata> instanceMetadataField;

        private string idField;

        public InstanceMetadataSet()
        {
            this.instanceMetadataField = new List<InstanceMetadata>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public List<InstanceMetadata> InstanceMetadata
        {
            get
            {
                return this.instanceMetadataField;
            }
            set
            {
                this.instanceMetadataField = value;
            }
        }

        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    public partial class InstanceMetadataSets
    {

        private Annotation annotationField;

        private List<InstanceMetadataSet> instanceMetadataSetField;

        public InstanceMetadataSets()
        {
            this.instanceMetadataSetField = new List<InstanceMetadataSet>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public List<InstanceMetadataSet> InstanceMetadataSet
        {
            get
            {
                return this.instanceMetadataSetField;
            }
            set
            {
                this.instanceMetadataSetField = value;
            }
        }
    }

    public partial class Identifier
    {

        private string langField;

        private string identifier1Field;

        private string valueField;

        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        public string Identifier1
        {
            get
            {
                return this.identifier1Field;
            }
            set
            {
                this.identifier1Field = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType = "normalizedString")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public partial class LongName
    {

        private string langField;

        private string identifierField;

        private string valueField;

        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType = "normalizedString")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public partial class ShortName
    {

        private string langField;

        private string valueField;

        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType = "token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public partial class Identification
    {

        private Annotation annotationField;

        private ShortName shortNameField;

        private List<LongName> longNameField;

        private string versionField;

        private string canonicalUriField;

        private string canonicalVersionUriField;

        private List<string> locationUriField;

        private List<string> alternateFormatLocationUriField;

        private IdentificationAgency agencyField;

        public Identification()
        {
            this.agencyField = new IdentificationAgency();
            this.alternateFormatLocationUriField = new List<string>();
            this.locationUriField = new List<string>();
            this.longNameField = new List<LongName>();
            this.shortNameField = new ShortName();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public ShortName ShortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }

        public List<LongName> LongName
        {
            get
            {
                return this.longNameField;
            }
            set
            {
                this.longNameField = value;
            }
        }

        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        public string CanonicalUri
        {
            get
            {
                return this.canonicalUriField;
            }
            set
            {
                this.canonicalUriField = value;
            }
        }

        public string CanonicalVersionUri
        {
            get
            {
                return this.canonicalVersionUriField;
            }
            set
            {
                this.canonicalVersionUriField = value;
            }
        }

        public List<string> LocationUri
        {
            get
            {
                return this.locationUriField;
            }
            set
            {
                this.locationUriField = value;
            }
        }

        public List<string> AlternateFormatLocationUri
        {
            get
            {
                return this.alternateFormatLocationUriField;
            }
            set
            {
                this.alternateFormatLocationUriField = value;
            }
        }

        public IdentificationAgency Agency
        {
            get
            {
                return this.agencyField;
            }
            set
            {
                this.agencyField = value;
            }
        }
    }

    public partial class IdentificationAgency
    {

        private ShortName shortNameField;

        private List<LongName> longNameField;

        private List<Identifier> identifierField;

        public IdentificationAgency()
        {
            this.identifierField = new List<Identifier>();
            this.longNameField = new List<LongName>();
            this.shortNameField = new ShortName();
        }

        public ShortName ShortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }

        public List<LongName> LongName
        {
            get
            {
                return this.longNameField;
            }
            set
            {
                this.longNameField = value;
            }
        }

        public List<Identifier> Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
    }

    public partial class ValueList
    {

        private Annotation annotationField;

        private Identification identificationField;

        private string idField;

        private string baseField;

        private string uriField;

        private string masqueradeUriField;

        private string keyField;

        public ValueList()
        {
            this.identificationField = new Identification();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public Identification Identification
        {
            get
            {
                return this.identificationField;
            }
            set
            {
                this.identificationField = value;
            }
        }

        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }

        public string uri
        {
            get
            {
                return this.uriField;
            }
            set
            {
                this.uriField = value;
            }
        }

        public string masqueradeUri
        {
            get
            {
                return this.masqueradeUriField;
            }
            set
            {
                this.masqueradeUriField = value;
            }
        }

        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }

    public partial class ValueLists
    {

        private Annotation annotationField;

        private List<ValueList> valueListField;

        private string baseField;

        public ValueLists()
        {
            this.valueListField = new List<ValueList>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public List<ValueList> ValueList
        {
            get
            {
                return this.valueListField;
            }
            set
            {
                this.valueListField = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
    }

    public partial class ValueTest
    {

        private Annotation annotationField;

        private string idField;

        private string testField;

        public ValueTest()
        {
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string test
        {
            get
            {
                return this.testField;
            }
            set
            {
                this.testField = value;
            }
        }
    }

    public partial class ValueTests
    {

        private Annotation annotationField;

        private List<ValueTest> valueTestField;

        public ValueTests()
        {
            this.valueTestField = new List<ValueTest>();
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public List<ValueTest> ValueTest
        {
            get
            {
                return this.valueTestField;
            }
            set
            {
                this.valueTestField = value;
            }
        }
    }

    public partial class Include
    {

        private Annotation annotationField;

        private string baseField;

        private string uriField;

        public Include()
        {
            this.annotationField = new Annotation();
        }

        public Annotation Annotation
        {
            get
            {
                return this.annotationField;
            }
            set
            {
                this.annotationField = value;
            }
        }

        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }

        public string uri
        {
            get
            {
                return this.uriField;
            }
            set
            {
                this.uriField = value;
            }
        }
    }

    public partial class Title
    {

        private List<System.Xml.XmlNode> anyField;

        public Title()
        {
            this.anyField = new List<System.Xml.XmlNode>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlNode> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    public partial class AnnotationAppInfo
    {

        private List<System.Xml.XmlNode> anyField;

        public AnnotationAppInfo()
        {
            this.anyField = new List<System.Xml.XmlNode>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlNode> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
}
